src/Service.Host/client/src/index.js

margin is set by something to 8px causing horizontal scrollbar to appear, in stores is overridden but not sure what by. We could figure it out if anyone has any ideas or we can just do this and set it to 0 manually.
Stores from dev tools:
and purchasing with this change in dev tools:

set body margin to 0 to avoid screen flicker/horizontal scroll bar

---

src/Service.Host/client/src/helpers/pdf.js

- generating larger pdfs with lots on them was crazy slow at the max quality settings. Dropping scale down a bit shows huge speed improvement without any real noticeable quality dropoff.
- this is really just a stop gap fix, as I've not been able to get pdfs that span more than one page to work with the current implementation (adding an image of the page contents to a pdf file). You also can't select/copy text from the pdfs this method generates - not ideal - so looking into other solutions today

use better balance between quality and speed to avoid long waits

---

.gitignore
src/Facade/Services/IPartsReceivedReportFacadeService.cs
src/Facade/Services/PartsReceivedReportFacadeService.cs
src/Service.Host/.eslintrc.json
src/Service.Host/Program.cs
src/Service.Host/client/src/components/reports/PartsReceivedReport.js
src/Service/Extensions/HttpResponseExtensions.cs
src/Service/Modules/Reports/PartsReceivedReportModule.cs

- I didn't really like how we were doing csv responses (all of the csv -> stream business etc repeated across every report module / facade service) so I tried to move that stuff into a reusable method
- The Carter way of doing this sort of thing seems to be Extension methods to the Request/Response objects, so I stuck to that policy
- Let me know what y'all think and if we are happy I'll refactor all the csv exports to work this way
- could add this extension to Common.Carter if we so desire

Report exports

---

src/Service/Modules/PlCreditDebitNotesModule.cs

I missed this typo that got introduced in the carter 6 switch

fix param name

---

src/Domain.LinnApps/Suppliers/SupplierService.cs
src/Service.Host/client/src/components/supplierUtility/tabs/WhoseTab.js
tests/Unit/Domain.LinnApps.Tests/SupplierServiceTests/WhenCreating.cs

- stops them accidentally not setting this to 'No Person Assigned' and causing some data lookup errors when using the supplier

don't allow null vendor manager

---

src/Service.Host/client/src/components/POReqs/POReqUtility.js

could create multiple reqs if someone sat and spammed button or double clicked

reqs - set edit status to view on save click, stops spam multi creation 

---

src/Domain.LinnApps/Reports/PurchaseOrdersReportService.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrdersReportServiceTests/WhenGettingOrdsByPartReport.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrdersReportServiceTests/WhenGettingOrdsBySupplierReport.cs

+ tests. Just not displaying the values that get totaled up after the first delivery. Funny wee bool instead of checking seq == 1 is me being paranoid that we delete the first delivery, not sure whether that's possible or not but don't think it's a big deal

don't include values for second delivery in report totals

---

src/Service.Host/client/src/components/POReqs/POReqUtility.js

default to 1 for both and just stays at 1 if user tries to enter less.
+ let users change value fields while draft or auth wait state

stop qty or value being 0 on po reqs

---

src/Domain.LinnApps/Reports/ForecastWeekChangesReportService.cs
src/Service.Host/client/src/components/AcknowledgeOrdersUtility.js

- fixes an issue where seemingly sporadically some dates would end up being 11pm the day before the actual date when they got toISOString()'d
- presumably a tz issue as chopping of the timezone worked 
- I'll poke around and see if datepickers elswhere in the project have the same weird behaviour

Ack orders date input fix

---

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenFillingOutDetailsForNonSundryNonStockControlledPart.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenFillingOutDetailsForStockControlledFinishedGoodsPart.cs

- hopefully fixes #400 (not the Requested Date part - thats another issue altogether)
- Iain was calculating and setting these values in the purchaseOrderReducer which a) seems like a bad idea and b) only happens if you make a change to the quick-create form and dispatch some actions, hence wasn't working if you came from the MR and didnt change any fields
- so I moved these calculations to the domain service 'FillOut...' method where they belong

set detail values in domain service

---

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderOverrideValueQtyFields.cs

C# changes. Question is now do we remove recalculateDetailFields from the purchaseorder reducer? Going to submit that as a separate PR if consensus is yes

Update delivery on detail change

---

src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js

Current form checks that ourUnitPriceCurrency, orderUnitPriceCurrency, netTotalCurrency, detailTotalCurrency, baseNetTotal and baseDetailTotal all have values before enabling the save button. A FOC order requires all of these fields to equal 0 and therefore the condition isn't satisfied.
An alternative to the current check would be to check if each var is equal to or above zero as opposed to removing. Let me know thoughts. 
React test to for main form to follow that will test this in a new PR.

FOC - allow 0 for key fields

---

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
src/Service.Host/client/src/components/AcknowledgeOrdersUtility.js
src/Service.Host/client/src/components/ChangeRequests/CreateChangeRequest.js
src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenFillingOutOrderAndSupplierIsClosed.cs

- default to most recently selected date advised when acknowledging orders (as opposed to todays date)
- don't allow raising orders for closed suppliers
- replace typeaheads for new search components in purchase order quick-create screen - Let me know if you think thats a bad idea

Support tickets

---

src/Domain.LinnApps/Boms/BomReportsService.cs

- weird bug where trying to compare strings to ints in an oracle query causes the usual massive/exponential loss in performance, basically made the report never return data

convert string ids to ints before running query

---

src/Domain.LinnApps/Boms/ChangeRequestService.cs
src/Domain.LinnApps/Boms/IChangeRequestService.cs
src/Facade/Services/ChangeRequestFacadeService.cs
src/Facade/Services/IChangeRequestFacadeService.cs
src/Service.Host/client/src/components/ChangeRequests/ChangeRequestsSearch.js
src/Service/Modules/ChangeRequestModule.cs
tests/Integration/Integration.Tests/ChangeRequestModuleTests/WhenGettingBoardChangeRequests.cs
tests/Integration/Integration.Tests/ChangeRequestModuleTests/WhenSearchingChangeRequests.cs
tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenSearchingChangeRequests.cs
tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenSearchingChangeRequestsWithNoSearchTerm.cs
tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenUpdatingChangeRequest.cs

Ability to search change requests using wildcards either * or % work
The following work
- TESTASS3
- TESTASS*
- *3
- *LEWIS*
Would have liked a LINQ like that worked with EF but Regex not supported and hence clunky if to cope with these conditions and can't cope with something like PCAS */L1* but that's an edge case
also added a filter with ability to show recent live changes but will need Jacki to see if these values are useful or not

Wildsearch

---

src/Domain.LinnApps/PurchaseOrderReqs/PurchaseOrderReqService.cs
src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
src/Facade/Services/PurchaseOrderFacadeService.cs
src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
src/Service.Host/client/src/components/PurchaseOrders/purchaseOrderReducer.js
tests/Integration/Integration.Tests/PurchaseOrderModuleTests/WhenCreatingCreditOrder.cs
tests/Integration/Integration.Tests/PurchaseOrderModuleTests/WhenCreatingReturnsOrder.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingOrderFromReq.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingOrderFromReqAndCarriageValue.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingFOCPurchaseOrder.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingPurchaseOrder.cs

- distribute carriage price across unit prices when req is converted to order
- allow leigh to directly enter Nominal Codes since she knows em off by heart
- stops supplier notes that consist of nothing but carriage returns from triggering the popup
- addresses #508 
- change Typeaheads to Search's on the PO form

Misc tickets

---

src/Domain.LinnApps/Boms/BomChangeService.cs
src/Service.Host/client/src/components/BomUtility/BomUtility.js
src/Service.Host/client/src/hooks/useExpandNodesWithChildren.js
tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenDeletingAllFromBom.cs

- nuke a bom detail if user is doing the 'Delete All' process and said detail was added by the current CRF (since it never made it onto the bom)
- don't allow copying onto assembliesthat haven't been 'Saved' onto the bom yet
- ui tweaks

Bom copy delete replace fixes

---

src/Domain.LinnApps/Mailers/PurchaseOrderRemindersMailer.cs
src/Service.Host/client/src/components/__tests__/boards/Board.test.js
src/Service.Host/client/src/components/boards/Board.js
src/Service.Host/client/src/components/boards/BoardTab.js
src/Service.Host/client/src/components/boards/RevisionTab.js
src/Service.Host/views/PurchaseOrder.cshtml

- use trim() stop whitespaces at start of supplier contacts email address busting the po reminder emails 
- default some dropdowns to No on the Boards Ut
- stop create or update of board with no PCB Part Number on the revision, at jackis request
- remove redundant email address from PO pdfs

Support odds and ends

---

src/Domain.LinnApps/Suppliers/SupplierService.cs

Pretty sure it was whitespace that was busting the oracle job that sends these emails... so as a preventative measure:

remove whitespace

---

src/Domain.LinnApps/Boms/ChangeRequestService.cs
tests/Integration/Integration.Tests/ChangeRequestModuleTests/ContextBase.cs
tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/ContextBase.cs
tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenMakingLiveWouldResultInDuplicateDetails.cs
tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenMakingLiveWouldResultInNonLivePartOnLivePartBom.cs
tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/ContextBase.cs

- I didn't realise you could make selected changes live without making the whole crf live
- so needed to make sure any new live / nonlive checks I had added were only applied to specific selected changeIds where appropriate, and not just the whole CRF (since sometimes individual changes on the CRF are valid to be made LIVE when the whole thing isn't

fix bug that was stopping individual changes on a crf being made live

---

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderDeliveryService.cs
src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingPurchaseOrder.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs
tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderOverrideValueQtyFields.cs

Updated everywhere we are using the BaseOurUnitPrice to get a total to be 5 decimal places instead of 2 - please check these are all necessary.

BaseOurUnitPrice decimal places

---

src/Domain.LinnApps/Reports/OutstandingPoReqsReportService.cs
src/Service.Host/client/src/components/POReqs/POReqUtility.js

really should return a descriptive message of what's happening but at least displaying the 2nd auth gives a clue for now.

improve situation where authorising po req apparently does nothing ticket 18928 

---

src/Domain.LinnApps/PurchaseOrders/PurchaseOrder.cs
src/Facade/ResourceBuilders/PurchaseOrderResourceBuilder.cs
src/Persistence.LinnApps/Repositories/PurchaseOrderRepository.cs
src/Persistence.LinnApps/ServiceDbContext.cs

RETSU defaults the debit note according to the returns order based on the RETURNS_ORDER_NUMBER field of the debit notes.
This change to purchasing logic is just to support that
Annoyingly there is also a link between debit notes and the original purchase order which is why the link rel is ret-credit-debit-note not credit-debit-note

returns order debit note link

---

.travis.yml
src/Domain.LinnApps/Domain.LinnApps.csproj
src/Domain.LinnApps/Reports/Models/SupplierSpendWithTotals.cs
src/Domain.LinnApps/Reports/SpendsReportService.cs
src/Domain/Domain.csproj
src/Facade/Facade.csproj
src/IoC/IoC.csproj
src/Messaging.Host/Dockerfile
src/Messaging.Host/Messaging.Host.csproj
src/Messaging/Messaging.csproj
src/Persistence.LinnApps/Persistence.LinnApps.csproj
src/Persistence.LinnApps/Repositories/SupplierSpendsRepository.cs
src/Persistence/Persistence.csproj
src/Proxy/Proxy.csproj
src/Resources/Resources.csproj
src/Scheduling.Host/Dockerfile
src/Scheduling.Host/Scheduling.Host.csproj
src/Service.Host/Dockerfile
src/Service.Host/Service.Host.csproj
src/Service.Host/client/src/components/reports/SpendBySupplierOptions.js
src/Service/Service.csproj
src/Tools/Tools.csproj
tests/Integration/Integration.Scheduling.Tests/Integration.Scheduling.Tests.csproj
tests/Integration/Integration.Tests/Integration.Tests.csproj
tests/Unit/Domain.LinnApps.Tests/Domain.LinnApps.Tests.csproj
tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/WhenGettingSupplierReport.cs
tests/Unit/Domain.Tests/Domain.Tests.csproj
tests/Unit/Facade.Tests/Facade.Tests.csproj
tests/Unit/Messaging.Tests/Messaging.Tests.csproj
tests/Unit/Proxy.Tests/Proxy.Tests.csproj

- quick report enhancement
- but also in keeping with my new rule (if you want to add an enhancement or new feature you also have to do some maintenance).... dotnet9.0 upgrade!
- Admittedly this is quite lowhanging fruit as far as maintenance is concerned - now that we dont have many non-dotnet depencies, upgrading seems as trivial as incrementing the target framework versions... let me know if you think I'm forgetting some subtleties

extend spend by supplier report to include FY before last
