linn/purchasing

src/Facade/Facade.csproj, src/Facade/Services/PartSupplierFacadeService.cs, src/Facade/Services/SigningLimitFacadeService.cs, src/Facade/Services/SupplierFacadeService.cs, src/Facade/Services/ThingFacadeService.cs, src/Service.Host/package-lock.json, src/Service.Host/package.json, src/Service/Modules/SigningLimitModule.cs, tests/Unit/Facade.Tests/Facade.Tests.csproj
PR early due to breaking change....
=> backend of delete with breaking change to facade service.

src/Service.Host/client/src/components/App.js, src/Service.Host/client/src/components/__tests__/App.test.js
- you can just mock out the redux state that useSelector will act on as shown
=> example of how to get stuff from redux store into components for testing

src/Service.Host/.eslintrc.json, src/Service.Host/client/src/components/App.js, src/Service.Host/client/src/components/__tests__/App.test.js
- example of how to test a redux action is dispatched with correct parameters in the useDispatch world. action creator functions no longer arrive  in the component as props but we can use jest.spyOn to watch for them being called
=> Dispatch example

src/Service.Host/client/src/middleware/itemCreated.js
...I'll try write tests to stop this happening again, but just a fix for now before anyone complains
=> Fix middleware since I broke it in my last PR

src/Domain.LinnApps/Reports/PurchaseOrdersReportService.cs, src/Facade/Services/IPurchaseOrderReportFacadeService.cs, src/Facade/Services/PurchaseOrderReportFacadeService.cs, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/__tests__/reports/SuppliersWithUnacknowledgedOrders.test.js, src/Service.Host/client/src/components/__tests__/reports/UnacknowledgedOrdersReport.test.js, src/Service.Host/client/src/components/reports/SuppliersWithUnacknowledgedOrders.js, src/Service.Host/client/src/components/reports/UnacknowledgedOrdersReport.js, src/Service.Host/client/src/reducers/index.js, src/Service/Modules/Reports/PurchaseOrdersReportModule.cs, tests/Integration/Integration.Tests/PurchaseOrdersReportModuleTests/WhenGettingUnacknowledgedOrdersExport.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrdersReportServiceTests/WhenGettingUnacknowledgedOrdersReport.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrdersReportServiceTests/WhenGettingUnacknowledgedOrdersReportForAllSuppliers.cs, tests/Unit/Facade.Tests/PurchaseOrdersReportServiceTests/WhenGettingUnacknowledgedOrdersExport.cs
=> Unack client

src/Domain.LinnApps/Domain.LinnApps.csproj, src/Domain.LinnApps/Reports/PurchaseOrdersReportService.cs, src/Facade/Facade.csproj, src/Resources/RequestResources/UnacknowledgedOrdersRequestResource.cs, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/reports/SuppliersWithUnacknowledgedOrders.js, src/Service.Host/package-lock.json, src/Service.Host/package.json, src/Service/Modules/Reports/PurchaseOrdersReportModule.cs
+ brings in library code updates
=> add name to csv file and fix routing of redirects

src/IoC/ServiceExtensions.cs
- my last PR formatted this file all weird for some reason, so just reverting
=> fix formatting

src/Service.Host/client/src/components/__tests__/supplierUtility.js/Supplier.test.js
- more tests. not quite tested absolutely everything but getting there
=> Supplier ut  tests

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderReqState.cs, src/Facade/ResourceBuilders/PurchaseOrderReqResourceBuilder.cs, src/Facade/ResourceBuilders/PurchaseOrderReqStateResourceBuilder.cs, src/Facade/Services/PurchaseOrderReqFacadeService.cs, src/Facade/Services/PurchaseOrderReqStateFacadeService.cs, src/IoC/HandlerExtensions.cs, src/IoC/PersistenceExtensions.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/PurchaseOrderReqRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/PurchaseOrderReqStateResource.cs, src/Resources/SearchResources/PurchaseOrderReqSearchResource.cs, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/actions/purchaseOrderReqApplicationStateActions.js, src/Service.Host/client/src/actions/purchaseOrderReqStatesActions.js, src/Service.Host/client/src/components/App.js, src/Service.Host/client/src/components/POReqSearch.js, src/Service.Host/client/src/components/POReqUtility.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/itemTypes.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/client/src/reducers/purchaseOrderReqStates.js, src/Service.Host/client/src/reducers/purchaseOrderReqs.js, src/Service/Modules/PurchaseOrderModule.cs, src/Service/ResultHandlers/PurchaseOrderReqApplicationStateHandler.cs, tests/Integration/Integration.Tests/PurchaseOrderModuleTests/WhenGettingPOReqApplicationState.cs, tests/Integration/Integration.Tests/PurchaseOrderModuleTests/WhenGettingReqStates.cs, tests/Integration/Integration.Tests/PurchaseOrderModuletests/ContextBase.cs
search page added, create properly implemented, required fields checked before save & blue_req_states pulled in now
Haven't yet emphasised some fields that are required like country typeahead etc - required doesn't seem to add the nice wee star to them at mo. If anyone's got an existing solution to that pls let me know
=> Blue req ut v1

src/Domain.LinnApps/Reports/WhatsDueInReportService.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenFilteringBySupplier.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenFilteringByVendorManager.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenGettingReport.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenOrderingByDate.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenOrderingBySupplier.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenOrderingByTotalValue.cs
I somehow forgot to add the most important column to the report...
=> add missing column

src/Domain.LinnApps/PurchaseOrders/OverbookAllowedByLog.cs, src/Facade/Services/PurchaseOrderFacadeService.cs, src/IoC/PersistenceExtensions.cs, src/Persistence.LinnApps/Persistence.LinnApps.csproj, src/Persistence.LinnApps/Repositories/OverbookAllowedByLogRespository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/client/src/components/OverbooksSearch.js, src/Service/Modules/PurchaseOrderModule.cs, tests/Integration/Integration.Tests/PurchaseOrderModuletests/WhenGettingPurchaseOrder.cs, tests/Integration/Integration.Tests/PurchaseOrderModuletests/WhenUpdatingPurchaseOrders.cs, tests/Unit/Facade.Tests/PurchaseOrderServiceTests/ContextBase.cs
Using Richard's SaveToLog contribution to Common that SignalLimitLog is using in my facade service. Just double checking but it doesn't seem that the PL_OVERBOOK_ALLOWED_BY table - any idea where I'm going wrong here?
=> Overbook Log Update

src/Service.Host/client/src/components/POReqs/POReqUtility.js, src/Service.Host/client/src/components/reports/OutstandingPoReqsReport.js
Could now give links for finance, orders etc ie ?state=FINANCE%20WAIT and loads relevant data straight away
+ fix description typo for dept search on req ut
=> give outstanding reqs report url param to pre-select state

src/Proxy/Proxy.csproj, src/Service/Service.csproj, tests/Integration/Integration.Tests/PrefSupReceiptsReportModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/PrefSupReceiptsReportModuleTests/WhenGettingReport.cs
upgrade mimekit.
upgrade identity server within major version
=> add missing tests

src/Domain.LinnApps/Reports/PrefSupReceiptsReportService.cs, src/Service.Host/client/src/components/reports/PrefSupReceiptsReport.js
a couple of bits of Andrew McV feedback on the report and the ability to call it with query strings from the dashboard
=> Receipts feedback

src/Domain.LinnApps/Reports/PrefSupReceiptsReportService.cs
simple one file report to sort report how andrew wants it sorted
=> sorting on report

src/Domain.LinnApps/PurchaseOrderReqs/PurchaseOrderReqService.cs, src/IoC/ServiceExtensions.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenUpdating.cs
+ don't change req number - was effectively deleting them if you updated anything
=> reqs - cc sender in authorisation request emails

src/Service.Host/client/src/components/reports/PrefSupReceiptsReport.js
pr refactor with stringfy didn't work so back to long way but with moment to avoid toISOString() badness
=> make work again

src/Service.Host/client/src/components/reports/PrefSupReceiptsReport.js
two tweaks to receipts report
- loads if query string present (doesn't wait on run report)
- attempt to get round production american date problems with export button
=> Reporttweaks

src/Service.Host/client/src/components/reports/PrefSupReceiptsReport.js
fix silly infinite despatch bug
=> Dontbestupid

src/Service.Host/client/src/components/POReqs/POReqUtility.js
was parsing int so total never had decimal places and so some are wrong. Will check recents
=> po reqs - fix decimal places being cut off

src/Domain.LinnApps/PurchaseOrderReqs/PurchaseOrderReqService.cs, src/Domain.LinnApps/PurchaseOrders/PurchaseOrder.cs, src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Facade/Facade.csproj, src/Facade/ResourceBuilders/AddressResourceBuilder.cs, src/Facade/ResourceBuilders/PurchaseOrderResourceBuilder.cs, src/Facade/Services/IPurchaseOrderFacadeService.cs, src/Facade/Services/PurchaseOrderFacadeService.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/PurchaseOrderRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/PurchaseOrderResource.cs, src/Service.Host/client/src/components/POReqs/POReqSearch.js, src/Service.Host/client/src/components/POReqs/POReqUtility.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderPrintout.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/views/PurchaseOrder.cshtml, src/Service.Host/views/_PODetail.cshtml, src/Service/Modules/PurchaseOrderModule.cs, tests/Integration/Integration.Tests/PurchaseOrderModuleTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenUpdating.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenUpdatingButClosedSupplier.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenUpdatingButSupplierOnHold.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenUpdatingStockControlledPart.cs, tests/Unit/Facade.Tests/PurchaseOrderServiceTests/ContextBase.cs
Planning on using this to render html and send to pdf service for generating pdfs on backend. Can view the html in browser for debugging, see purchase orders module
- on reqs front end have swapped order of dept and nom as Les Baird spoke to me and thinks would be more clear
- Couple of missing checks to reqs backend: check part is not stock controlled (spoke to Andrew Mcv and they don't raise po reqs for stock controlled parts); check if ok to order - pl_orders pack had this but it just checks supplier is not closed or on hold, so checked these in C#
=> v0 of razor html rendering + reqs fix & backend checks

src/Service.Host/client/src/components/POReqs/POReqUtility.js
and automatically close dialog box when create order
=> reqs - let finance edit unit price and qty after draft stage

src/Facade/Facade.csproj, src/Facade/ResourceBuilders/PurchaseOrderResourceBuilder.cs, src/Persistence.LinnApps/Repositories/PurchaseOrderRepository.cs, src/Persistence.LinnApps/Repositories/PurchaseOrderReqRepository.cs, src/Resources/PurchaseOrderResource.cs, src/Service.Host/client/src/components/POReqs/POReqSearch.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service/Modules/PurchaseOrderReqModule.cs, tests/Unit/Facade.Tests/Facade.Tests.csproj
I did this wee bit last thurs with covid brain then forgot to click create amongst the testing +ve madness
=> po - small improvements of front end ui

src/Service.Host/client/src/components/App.js
Left out from main submission, correcting that here
=> add Shortages to app.js

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Facade/Services/PurchaseOrderFacadeService.cs, src/IoC/ServiceExtensions.cs, tests/Integration/Integration.Tests/PurchaseOrderModuleTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenSendingPdfEmail.cs, tests/Unit/Facade.Tests/PurchaseOrderServiceTests/ContextBase.cs
not sure how to find the logs yet to check but will send some on sys with this there and see
- not sure if I'll get an actual error thrown if the email service fails, anyone know? 
- Does anyone know what I'm meant to put in the list of LoggingProperty? Fields I want logged like supplier and email maybe? I just put them in the message
=> try logging email success and failures

src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
=> Minor Front End Update to get icon working

src/Domain.LinnApps/ExternalServices/ILedgerPeriodPack .cs, src/Domain.LinnApps/Reports/ISpendsReportService.cs, src/Domain.LinnApps/Reports/Models/SupplierSpendWithTotals.cs, src/Domain.LinnApps/Reports/SpendsReportService.cs, src/Facade/Services/ISpendsReportFacadeService.cs, src/Facade/Services/SpendsReportFacadeService.cs, src/IoC/ServiceExtensions.cs, src/Proxy/LedgerPeriodPack.cs, src/Resources/RequestResources/SpendBySupplierByDateRangeReportRequestResource.cs, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/actions/spendBySupplierByDateRangeActions.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/reports/SpendBySupplierByDateRange.js, src/Service.Host/client/src/components/reports/SpendBySupplierByDateRangeOptions.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/client/src/reducers/spendBySupplierByDateRangeReport/index.js, src/Service.Host/client/src/reducers/spendBySupplierByDateRangeReport/options.js, src/Service.Host/client/src/reducers/spendBySupplierByDateRangeReport/results.js, src/Service.Host/client/src/reportTypes.js, src/Service/Modules/Reports/SpendsReportModule.cs, tests/Integration/Integration.Tests/SpendsReportModuleTests/WhenGettingSpendBySupplierByDateRangeExport.cs, tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/WhenGettingSupplierReportByDateRange.cs
Split into separate report as per Andrew McV's request. Simplified version of the report but can search between dates. Uses LedgerPack to determine correct period.
=> SpendBySupplier report with selectable date range using LedgerPack

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderDetail.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/views/PurchaseOrder.cshtml
not sure if I thought it was unused or just missed it but Stewart raised a ticket about it
=> add drawing ref to purchase order pdf when drawing ref there

src/Service.Host/client/src/components/PurchaseOrders/AllowPurchaseOrderOverbook.js, src/Service.Host/client/src/components/PurchaseOrders/OverbooksSearch.js
Change from Typeahead to InputField for OrderNumber.
Fix button at bottom .
=> OB Search Changes

src/Service.Host/client/src/components/POReqs/POReqSearch.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrdersSearch.js
Remove Typeaheads and allow Purch to just go to desired order.
Played around a bit with the PurchOrderReq and thought some helper text may look better than a tooltip? Feel free to voice opinion though
=> Amend search on PurchOrder and PurchOrderReq

src/Domain.LinnApps/PurchaseOrders/PurchaseOrder.cs, src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Facade/ResourceBuilders/PurchaseOrderResourceBuilder.cs, src/Facade/Services/UnitsOfMeasureService.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrdersSearch.js
- make loading/spinner work on create too, since always either loading po in or waiting for post from backend, always do get item loading
- change title of wizard page
- hardcode damages percent to 2 for now
=> tidy ups to quick-create wizard page

src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
Small PR (splitting changes out into different branches)
=> View deliveries at glance

src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js
i put this in as a kind of placeholder as I didn't know if it was right but I guess the dates should at least be consistent
=> what kind of date

src/Service.Host/client/src/components/BomTree.js, src/Service.Host/client/src/configureStore.js, src/Service.Host/client/src/middleware/receiveBomTreeNodes.js, src/Service.Host/client/src/reducers/bomTreeNodes.js
traverse the bom tree client-side so we can do each branch in parallel and load big trees quickly
=> Bom tree ++

src/Domain.LinnApps/Reports/WhatsDueInReportService.cs, src/Facade/Services/WhatsDueInReportFacadeService.cs, tests/Integration/Integration.Tests/WhatsDueInReportModuleTests/WhenGettingExport.cs, tests/Integration/Integration.Tests/WhatsDueInReportModuleTests/WhenGettingReport.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenGettingReport.cs, tests/Unit/Domain.LinnApps.Tests/WhatsDueInReportServiceTests/WhenOrderingByDate.cs
=> fix report date issues

Purchasing.sln, pl_automatic_orders_view.sql, src/Facade/ResourceBuilders/MrReportResourceBuilder.cs, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrdersAuthSend.js, tests/Unit/Facade.Tests/ResourceBuilderTests/MrReportResourceBuilderTests/WhenBuildingReportResourceForMr.cs
tickets 16292 and 16299 and closes #374
=> 3 small changes 

src/Scheduling.Host/Jobs/SupplierAutoEmailsScheduler.cs, tests/Integration/Integration.Scheduling.Tests/SupplierAutoEmailsSchedulerTests/When6AmOnMonday.cs
I didn't get around to fixing this / switching off the old emails... so just disabling them again for now so supplier don't get duplicates
=> disable order book emails

src/Domain.LinnApps/PurchaseOrders/PurchaseOrder.cs, src/Domain.LinnApps/Reports/PurchaseOrdersReportService.cs, src/Facade/ResourceBuilders/PurchaseOrderResourceBuilder.cs, src/Persistence.LinnApps/Repositories/PurchaseOrderRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/PurchaseLedgerResource.cs, src/Resources/PurchaseOrderResource.cs, src/Service.Host/client/src/components/PurchaseOrders/PlInvRecDialog.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
- this is just the data Alison cares about. I'll merge this then check if Stewart needs more
=> add dialog

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Facade/ResourceBuilders/PurchaseOrderDeliveryResourceBuilder.cs, src/Facade/Services/PurchaseOrderFacadeService.cs, src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/PurchaseOrders/purchaseOrderReducer.js, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingPurchaseOrder.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenFillingOutDetailsForStockControlledRawMaterialPart.cs
for #401 
- all works fine except date pickers show the wrong day of the week
=> Requested date business

src/Domain.LinnApps/Reports/ISpendsReportService.cs, src/Domain.LinnApps/Reports/Models/SupplierSpend.cs, src/Domain.LinnApps/Reports/SpendsReportService.cs, src/Facade/Services/ISpendsReportFacadeService.cs, src/Facade/Services/SpendsReportFacadeService.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/actions/spendByPartByDateActions.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/reports/SpendByPartByDate.js, src/Service.Host/client/src/components/reports/SpendBySupplierByDateRange.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/client/src/reducers/spendByPartByDateReport/index.js, src/Service.Host/client/src/reducers/spendByPartByDateReport/options.js, src/Service.Host/client/src/reducers/spendByPartByDateReport/results.js, src/Service.Host/client/src/reportTypes.js, src/Service/Modules/Reports/PrefSupReceiptsReportModule.cs, src/Service/Modules/Reports/SpendsReportModule.cs, tests/Integration/Integration.Tests/SpendsReportModuleTests/WhenGettingSpendByPartByDateReport.cs, tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/WhenGettingPartByDateReport.cs, tests/Unit/Domain.LinnApps.Tests/SpendsReportServiceTests/WhenGettingPartReport.cs
New drill down report to match spend by supplier by date range drill down.
And remove repeated to call to part repo in other report to make it much faster
=> new drill down report

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderOverrideValueQtyFields.cs
Ensure we are using DELIVERY QTY rather than DETAIL.
=> Delivery Total Refinements + Multi Delivery test

src/Domain.LinnApps/PartSuppliers/PartSupplierService.cs, src/Domain.LinnApps/Reports/MrOrderBookReportService.cs, src/Service.Host/client/src/components/Search.js, src/Service.Host/client/src/components/__tests__/partSupplierUtility/PartSupplier.test.js, src/Service.Host/client/src/components/partSupplierUtility/PartSupplier.js, src/Service.Host/client/src/components/partSupplierUtility/tabs/ManufacturerTab.js, src/Service.Host/client/src/components/partSupplierUtility/tabs/PartSupplierTab.js, src/Service.Host/client/src/components/supplierUtility/Supplier.js, src/Service.Host/client/src/components/supplierUtility/SuppliersSearch.js, src/Service.Host/client/src/components/supplierUtility/tabs/WhereTab.js, src/Service.Host/package-lock.json, src/Service.Host/package.json, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenCreating.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenCreatingAndNoDesignation.cs
- +1 example usage
- will show and tell this / get user feedback before I decide whether to add it to the common libary
=> Experimental search componenet

src/Domain.LinnApps/PurchaseOrderReqs/PurchaseOrderReqService.cs, src/Facade/Services/PurchaseOrderReqFacadeService.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingAndNoRequestedByName.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingAndRequestedByName.cs
=> fix remark bug

src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingFOCPurchaseOrder.cs
Used for FOC orders. Requested by Scott.
=> Allow Purchasing to set OurUnitPriceCurrency to 0

src/Domain.LinnApps/Boms/BomDetail.cs, src/Domain.LinnApps/Boms/BomReportsService.cs, src/Domain.LinnApps/Boms/IBomReportsService.cs, src/Domain.LinnApps/Parts/Part.cs, src/Domain.LinnApps/Reports/MrOrderBookReportService.cs, src/Facade/Services/BomReportsFacadeService.cs, src/Facade/Services/IBomReportsFacadeService.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/BomDetailRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/actions/partsOnBomReportActions.js, src/Service.Host/client/src/components/BomTree.js, src/Service.Host/client/src/components/BomTreeOptions.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/reports/PartsOnBomReport.js, src/Service.Host/client/src/hooks/useInitialise.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/client/src/reducers/partsOnBomReport.js, src/Service.Host/client/src/reportTypes.js, src/Service/Modules/BomModule.cs, tests/Integration/Integration.Tests/BomModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenGettingPartsOnBomExport.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenGettingPartsOnBomReport.cs, tests/Integration/Integration.Tests/MrOrderBookReportModuleTests/WhenGettingExport.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/WhenGettingReport.cs, tests/Unit/Domain.LinnApps.Tests/Domain.LinnApps.Tests.csproj
- decided not to combine with cost report, will do that next
=> Bom print and cost reports

src/Domain.LinnApps/Boms/BomDetail.cs, src/Domain.LinnApps/Boms/BomDetailComponent.cs, src/Domain.LinnApps/Boms/BomReportsService.cs, src/Domain.LinnApps/Boms/BomTreeService.cs, src/Domain.LinnApps/Boms/Models/BomCostReport.cs, src/Facade/Services/BomReportsFacadeService.cs, src/Persistence.LinnApps/Repositories/BomDetailRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/BomCostReportResource.cs, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/reports/BomCostReport.js, src/Service.Host/client/src/components/reports/BomCostReportOptions.js, src/Service/Modules/BomModule.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/WhenGettingBomCostsReportSplitBySubAssembly.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/WhenGettingPartsOnBomReport.cs
- assorted tweaks resulting from meeting with jacki yesterdat
=> Finish bom costs and other misc todos

src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
reinstate the Qty Override button for create mode
=> Revert removal of Qty Override button

src/Facade/ResourceBuilders/ChangeRequestResourceBuilder.cs, src/Persistence.LinnApps/Repositories/ChangeRequestRepository.cs, src/Service.Host/client/src/components/ChangeRequests/ChangeRequestsSearch.js
Very basic change request search on new part number using existing search
Jacki may eventually want a more advanced search
=> Basicsearch

src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js
put a maxlength on remarks of 500
=> maxlength on remarks

src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js
fixes part number no longer being visible after selecting credit / returns original order number. 
fixes ticket 16735 - can't select 0.5
=> ticket fixes

src/Domain.LinnApps/Boms/ChangeRequest.cs, src/Domain.LinnApps/Boms/ChangeRequestService.cs, src/Domain.LinnApps/Boms/IChangeRequestService.cs, src/Facade/Services/ChangeRequestFacadeService.cs, src/Service.Host/client/src/components/ChangeRequests/Tabs/MainTab.js, src/Service/Modules/ChangeRequestModule.cs, tests/Integration/Integration.Tests/ChangeRequestModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/ChangeRequestModuleTests/WhenUpdatingChangeRequest.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestTests/WhenAppovedAndCheckingCanEditWithRights.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestTests/WhenCancelledAndCheckingCanEdit.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestTests/WhenProposedAndCheckingCanEdit.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/ContextBase.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenUpdatingChangeRequest.cs
update change request story which currently only allows editing of the reason and description fields only while PROPOS/ACCEPT with admin privs
=> updating story on change request

src/Facade/Services/PurchaseOrderFacadeService.cs, src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, src/Service.Host/client/src/components/PurchaseOrders/purchaseOrderReducer.js
Speculative change to try and alleviate ticket  http://pchelpdesk.linn.co.uk/scp/tickets.php?id=16706
Will it work? Who knows?
=> allow typing of part number and supplier id

src/Domain.LinnApps/Parts/Part.cs, src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Persistence.LinnApps/ServiceDbContext.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingOrderAndPartNotLive.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenCreatingPurchaseOrder.cs
- is this sensible? Should this only apply to stock controlled parts? @andrewfraser73
=> prohibit ordering non live parts

src/Facade/Services/ChangeRequestFacadeService.cs, src/Facade/Services/IChangeRequestFacadeService.cs, src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service.Host/client/src/hooks/useInitialise.js, src/Service/Modules/ChangeRequestModule.cs, tests/Integration/Integration.Tests/ChangeRequestModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/ChangeRequestModuleTests/WhenGettingAllChangeRequestsRelevantToABom.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/ContextBase.cs
- allow dropdown selection of any non-LIVE change request that pertains to this bom (i.e. that are for this bom specifically, or one of its sub assemblies) when editing bom via bom ut
=> bom-ut - expand crf selection

src/Domain.LinnApps/Boms/BomChange.cs, src/Domain.LinnApps/Boms/BomChangeDetail.cs, src/Domain.LinnApps/Boms/BomDetail.cs, src/Facade/ResourceBuilders/BomChangeResourceBuilder.cs, src/Persistence.LinnApps/Repositories/ChangeRequestRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/BomChangeResource.cs, src/Service.Host/client/src/components/ChangeRequests/BomChangeDetails.js, src/Service.Host/client/src/components/ChangeRequests/Tabs/BomChangesTab.js, src/Service.Host/client/src/components/ChangeRequests/Tabs/MainTab.js, tests/Integration/Integration.Tests/ChangeRequestModuleTests/WhenGettingChangeRequest.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeTests/WhenGettingBomChangeDetailsAndJustDeletions.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeTests/WhenGettingBomChangeDetailsAndNoBomDetails.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeTests/WhenGettingBomChangeDetailsForAReplace.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeTests/WhenGettingBomChangeDetailsForJustAdditions.cs
show a popup of bom change details on change requests could also form the basis of a crf print.
would have liked to a sort of nested datagrid view but datagrids within datagrids too ugly.
=> bom details

src/Persistence.LinnApps/ServiceDbContext.cs
changing where you declare the one to many relationship is the difference between it working and failing
=> to fix 500 on change request lookup

src/Service.Host/client/src/components/BomTree.js, src/Service.Host/client/src/components/BomUtility/BomUtility.js
- allows you to search for a part on the bom via the tree ui just like the old form
- works like ctrl + f, so flicks through matching results one by one if there is more than one
- I also made the page scroll to the current search result, although its  hacky/not very react-y and there might be a better way
=> Adv func search bom

src/Domain.LinnApps/Boms/Bom.cs, src/Domain.LinnApps/Boms/BomChangeService.cs, src/Domain.LinnApps/Boms/IBomChangeService.cs, src/Domain.LinnApps/ExternalServices/IBomPack.cs, src/Facade/Services/BomFacadeService.cs, src/Facade/Services/ChangeRequestFacadeService.cs, src/Facade/Services/IBomFacadeService.cs, src/IoC/ServiceExtensions.cs, src/Persistence.LinnApps/Repositories/BomRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Proxy/BomPack.cs, src/Resources/Boms/CopyBomResource.cs, src/Service.Host/client/src/actions/copyBomActions.js, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service.Host/client/src/processTypes.js, src/Service.Host/client/src/reducers/copyBom.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/package-lock.json, src/Service.Host/package.json, src/Service/Modules/BomModule.cs, tests/Integration/Integration.Tests/BomModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenCopyingBom.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenPostingBom.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenAddingAPartToItsOwnBom.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenAddingPartWithNoBomType.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenCopyingBom.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenCreatingNewBom.cs
- pre-support wip commit, but most of the bits are in place
=> Adv func copy bom

src/IoC/PersistenceExtensions.cs
- this line seems to have snuck in to the last merge to main
=> remove wrong registration

src/Domain.LinnApps/Boms/ChangeRequestService.cs, src/Facade/Services/ChangeRequestFacadeService.cs, src/Service.Host/client/src/components/ChangeRequests/ChangeRequest.js, src/Service.Host/client/src/components/ChangeRequests/ChangeRequestsSearch.js, src/Service.Host/client/src/components/ChangeRequests/ChangeTypes/AssemblyChange.js, src/Service.Host/client/src/components/ChangeRequests/CreateChangeRequest.js
- changes typeahead to <Search / > (with Andrew's blessing)
- fix some bugs I noticed when using this form over and over again to make change requests for bom ut testing
=> Fix change request bugs

src/Domain.LinnApps/Boms/BomChangeService.cs, src/Domain.LinnApps/Boms/IBomChangeService.cs, src/Facade/Services/BomFacadeService.cs, src/Facade/Services/IBomFacadeService.cs, src/Resources/Boms/BomFunctionResource.cs, src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service/Modules/BomModule.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenCopyingBom.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenDeletingAllFromBom.cs, tests/Integration/Integration.Tests/BomModuleTests/WhenExplodingSubAssembly.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenCopyingBom.cs
- support the 'append' style of bom copy
- allow adv functions to be carried out for any sub assembly as opposed to just the tree root as was the case before
- some ui improvements to remind the user what each adv func actually does
=> New adv functions bits

src/Domain.LinnApps/Boms/BomChangeService.cs, src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service.Host/client/src/components/__tests__/bomUtility/BomUtility.test.js, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenCreatingMultipleNewBoms.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenCreatingNewBom.cs, tests/Unit/Domain.LinnApps.Tests/BomChangeServiceTests/WhenUpdatingExistingDetailFields.cs
- adds functionality to allow creating and configuring multiple boms at once
- miraculously the domain service code already supported this since my most recent refactor (a nice win) so this PR is really just a tweak to the client and a test to confirm the domain service works :)
=> Make multiple boms at once

src/Service.Host/views/PurchaseOrder.cshtml
http://rndsupport.linn.co.uk/scp/tickets.php?id=16996
=> Supplier Designation Layout Tweak

src/Service.Host/client/src/components/BomVerificationHistoryUtility/CreateBomVerificationHistory.js, src/Service/Modules/BomVerificationHistoryModule.cs, tests/Integration/Integration.Tests/BomVerificationHistoryModuleTests/WhenCreatingBomVerificationHistoryEntry.cs
Had removed Get App causing a problem, reinstated and added tabbing.
=> Fix BomVer Typo

src/Domain.LinnApps/Boms/Models/BomTreeNode.cs, src/Domain.LinnApps/Reports/BomHistoryReportService.cs, src/Facade/Services/BomHistoryReportFacadeService.cs, src/Persistence.LinnApps/Repositories/BomDetailRepository.cs, src/Persistence.LinnApps/Repositories/ChangeRequestRepository.cs, src/Service.Host/client/src/components/BomHistoryReport.js, tests/Unit/Domain.LinnApps.Tests/BomHistoryReportServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/BomHistoryReportServiceTests/WhenIncludingSubAssemblies.cs, tests/Unit/Domain.LinnApps.Tests/Domain.LinnApps.Tests.csproj
- i finally settled on a way of making this work using recursion after about 3 days of bad ideas
=> Bom hist rep tests and probably fixes too

src/Scheduling.Host/Jobs/PurchaseOrderRemindersScheduler.cs
- just to test this works tomorrow morn
=> fix query to test tomorrow morning

src/Domain.LinnApps/Boms/ChangeRequestService.cs, src/Domain.LinnApps/Boms/IChangeRequestService.cs, src/Domain.LinnApps/Boms/Models/BoardComponentSummary.cs, src/Domain.LinnApps/ExternalServices/IPcasPack.cs, src/Facade/ResourceBuilders/BoardComponentSummaryResourceBuilder.cs, src/Facade/Services/ChangeRequestFacadeService.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Proxy/PcasPack.cs, src/Resources/Boms/BoardComponentSummaryResource.cs, src/Resources/RequestResources/ChangeRequestReplaceResource.cs, src/Service.Host/client/src/components/ChangeRequests/BomChangeReplace.js, src/Service.Host/client/src/components/ChangeRequests/ChangeRequestReplace.js, src/Service.Host/client/src/components/ChangeRequests/PcasChangeReplace.js, src/Service.Host/package-lock.json, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenReplaceOnAcceptedChangeRequestAndNotAuthorised.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenReplaceOnChangeRequest.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenReplaceOnChangeRequestWithGlobalReplace.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenReplaceOnNonExistentChangeRequest.cs
does the replace all version of pcas replace by calling the same PL/SQL as the form version
added a couple more links
=> v1 with the global replace

src/Domain.LinnApps/Boms/BomChangeDetail.cs, src/Facade/ResourceBuilders/ChangeRequestResourceBuilder.cs, src/Service.Host/client/src/components/ChangeRequests/Tabs/BomChangesTab.js, src/Service.Host/client/src/components/ChangeRequests/Tabs/MainTab.js, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenGettingApprovedChangeRequest.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenGettingProposedChangeRequest.cs
fix a few things for this afternoon's meeting
- move phase in button
- allow editing of live changes
=> some jacki feedback changes

src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/__tests__/purchaseOrders/PurchaseOrderUtility.test.js, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingCreditOrderConvValueQtyFields .cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderConvValueQtyFields.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingPurchaseOrderOverrideValueQtyFields.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderServiceTests/WhenUpdatingReturnsOrderConvValueQtyFields.cs
Disable on Create/within form itself.
=> Disable unit price change when Credit or Returns order

src/Service.Host/client/src/components/ChangeRequests/ChangeRequest.js
tiny tweak to refresh refresh change requests after phase ins
=> tiny tweak to refresh change requests after phase ins

src/Domain.LinnApps/PurchaseOrderReqs/PurchaseOrderReqService.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingAndNoDateRequiredSpecified.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingOrderFromReq.cs, tests/Unit/Domain.LinnApps.Tests/PurchaseOrderReqServiceTests/WhenCreatingOrderFromReqAndCarriageValue.cs
http://rndsupport.linn.co.uk/scp/tickets.php?id=17207
=> DateRequired must be future date

src/Domain.LinnApps/Suppliers/SupplierContact.cs, src/Domain.LinnApps/Suppliers/SupplierService.cs, src/Facade/ResourceBuilders/SupplierResourceBuilder.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Service.Host/client/src/components/supplierUtility/Supplier.js, src/Service.Host/client/src/components/supplierUtility/supplierReducer.js, src/Service.Host/client/src/components/supplierUtility/tabs/ContactTab.js, src/Service.Host/package-lock.json, tests/Unit/Domain.LinnApps.Tests/SupplierServiceTests/WhenDeletingAContact.cs, tests/Unit/Domain.LinnApps.Tests/SupplierServiceTests/WhenDeletingAContactLeavesNoMainInvoiceContact.cs, tests/Unit/Domain.LinnApps.Tests/SupplierServiceTests/WhenDeletingAContactLeavesNoMainOrderContact.cs
- from the clients point of view it looks like you are deleting contacts... but under the hood you are really just marking them as invalid to prevent data loss
=> Allow delete supp contacts

src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service.Host/client/src/components/BomUtility/BomUtilitySearch.js
Idea: Mimic the oracle functionality when you run a wildcard search, i.e. where it lets you flick through matching results with a prev/next button interface.
=> Bom utility search improvements

src/Service.Host/client/src/components/BomUtility/BomUtility.js, src/Service.Host/client/src/components/ChangeRequests/ChangeRequest.js, src/Service.Host/client/src/components/ChangeRequests/ChangeRequestsSearch.js, src/Service.Host/client/src/components/PrevNextButtons.js, src/Service.Host/client/src/hooks/usePreviousNextNavigation.js
- add the ability to flick through search results to the change request form
=> More search results flicking

src/Domain.LinnApps/Boms/BoardComponent.cs, src/Domain.LinnApps/Boms/BomReportsService.cs, src/Domain.LinnApps/Boms/CircuitBoardService.cs, src/Facade/Extensions/CircuitBoardResourceExtensions.cs, src/Facade/ResourceBuilders/CircuitBoardResourceBuilder.cs, src/Persistence.LinnApps/Repositories/CircuitBoardRepository.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/Boms/BoardComponentResource.cs, src/Service.Host/client/src/components/reports/BoardComponentSummaryReport.js, src/Service/Modules/Reports/BomReportsModule.cs, tests/Unit/Domain.LinnApps.Tests/BomReportsServiceTests/WhenGettingBoardComponentSummaryReport.cs
=> Board Print Get App/Speed up search

src/Domain.LinnApps/Boms/BomReportsService.cs, src/Domain.LinnApps/Boms/Models/BomCostReports.cs, src/Domain.LinnApps/Domain.LinnApps.csproj, src/Facade/Services/BomReportsFacadeService.cs, src/Facade/Services/IBomReportsFacadeService.cs, src/IoC/IoC.csproj, src/IoC/ServiceExtensions.cs, src/Service.Host/client/src/components/reports/BomCostReport.js, src/Service.Host/client/src/components/supplierUtility/tabs/ContactTab.js, src/Service.Host/views/BomCostReport.cshtml, src/Service/Modules/BomModule.cs, tests/Integration/Integration.Tests/BomModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/BomReportsModuleTests/ContextBase.cs
- also an example of using Linn.Common.Reporting in razor views, as per my last [PR in common](https://github.com/linn/common/pull/152)
- kind of a step towards providing a generic .ToPdf() conversion for the ResultsModel, possibly
=> pdf version of bom cost report

src/Facade/Services/PurchaseOrderFacadeService.cs, src/Resources/SearchResources/PurchaseOrderSearchResource.cs, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderLookUp.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderSearch.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrdersSearch.js, src/Service.Host/client/src/components/Root.js, src/Service/Modules/PurchaseOrderModule.cs
- this is a bit crude, i.e. just does a .Contains() style search on order details supplier designation and internal comments fields... but its probably good enough for now
=> Simple po narrative search

src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js
=> Get PO By Id instead of search

src/Domain.LinnApps/Boms/ChangeRequestService.cs, tests/Integration/Integration.Tests/ChangeRequestModuleTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/ChangeRequestServiceTests/WhenMakingLiveWouldResultInDuplicateDetails.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/ContextBase.cs
http://rndsupport.linn.co.uk/scp/tickets.php?id=18125
=> stop duplicate bom details going live

src/Domain.LinnApps/Reports/ShortagesReportService.cs
http://rndsupport.linn.co.uk/scp/tickets.php?id=18205
=> Shortages Report rejigging of columns

src/Service.Host/client/src/components/AcknowledgeOrdersUtility.js, src/Service.Host/client/src/components/BomHistoryReport.js, src/Service.Host/client/src/components/POReqs/POReqUtility.js, src/Service.Host/client/src/components/PurchaseOrderDeliveriesUtility.js, src/Service.Host/client/src/components/PurchaseOrders/CreatePurchaseOrderUt.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderSearch.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrdersAuthSend.js, src/Service.Host/client/src/components/partSupplierUtility/tabs/LifecycleTab.js, src/Service.Host/client/src/components/reports/OrdersByPartOptions.js, src/Service.Host/client/src/components/reports/OrdersBySupplierOptions.js, src/Service.Host/client/src/components/reports/PartsReceivedReport.js, src/Service.Host/client/src/components/reports/PrefSupReceiptsReport.js, src/Service.Host/client/src/components/reports/SpendBySupplierByDateRangeOptions.js, src/Service.Host/client/src/components/supplierUtility/tabs/LifecycleTab.js, src/Service.Host/package-lock.json
- whoever reviews just double check I didn't screw up any of the lines that are fishing out data from the redux store (I tried to mitigate against that unnecessary re-rendering issue rich showed us at show n tell)
=> fix po-del-dates

src/Service.Host/Startup.cs
seemed to work in finance, so same deal here
=> fix browser back / tab restores returning json bug

src/Service.Host/client/src/components/__tests__/supplierUtility/Supplier.test.js, src/Service.Host/client/src/components/supplierUtility/tabs/WhereTab.js
show address id in where supplier tab addresses
=> changes to show address Id on supplier ut where tab

src/Domain.LinnApps/Mailers/SupplierAutoEmailsMailer.cs, src/Domain.LinnApps/PurchaseOrders/PurchaseOrderService.cs, src/Domain.LinnApps/Suppliers/SupplierContact.cs, src/Domain.LinnApps/Suppliers/SupplierService.cs, src/Facade/ResourceBuilders/SupplierContactResourceBuilder.cs, src/Facade/Services/SupplierFacadeService.cs, src/Persistence.LinnApps/ServiceDbContext.cs, src/Resources/SupplierContactResource.cs, src/Service.Host/client/src/components/PurchaseOrders/PurchaseOrderUtility.js, src/Service.Host/client/src/components/supplierUtility/tabs/ContactTab.js, tests/Unit/Domain.LinnApps.Tests/SupplierAutoEmailsMailerTests/WhenSendingMonthlyForecastEmail.cs, tests/Unit/Domain.LinnApps.Tests/SupplierAutoEmailsMailerTests/WhenSendingMonthlyForecastEmailAndMultipleAddresses.cs
- allows a cc list to be set up for  a suppliers main order contact emails
- just commenting out some auto emails too at the moment since they are not in use anyway
=> cc lists n stuff

src/Domain.LinnApps/Boms/ChangeRequestService.cs, src/Domain.LinnApps/Boms/IChangeRequestService.cs, src/Facade/Services/ChangeRequestFacadeService.cs, src/Facade/Services/IChangeRequestFacadeService.cs, src/Service.Host/client/src/components/ChangeRequests/ChangeRequestsSearch.js, src/Service/Modules/ChangeRequestModule.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenSearchingChangeRequests.cs, tests/Unit/Facade.Tests/ChangeRequestFacadeServiceTests/WhenSearchingChangeRequestsWithNoSearchTerm.cs
for a ticket include the ability to search cancelled changes
=> allow change search to include cancelled

src/Domain.LinnApps/Exceptions/VendorManagerException.cs, src/Facade/ResourceBuilders/VendorManagerResourceBuilder.cs, src/Facade/Services/VendorManagerFacadeService.cs, src/Resources/VendorManagerResource.cs, src/Service.Host/client/src/actions/currentEmployeesActions.js, src/Service.Host/client/src/actions/index.js, src/Service.Host/client/src/actions/vendorManagerActions.js, src/Service.Host/client/src/components/Root.js, src/Service.Host/client/src/components/VendorManager.js, src/Service.Host/client/src/components/VendorManagers.js, src/Service.Host/client/src/itemTypes.js, src/Service.Host/client/src/reducers/currentEmployees.js, src/Service.Host/client/src/reducers/index.js, src/Service.Host/client/src/reducers/vendorManager.js, src/Service.Host/package-lock.json, src/Service.Host/package.json, src/Service/Modules/VendorManagerModule.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/ContextBase.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenCreatingVendorManager.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenCreatingVendorManagerAlreadyExists.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenGettingVendorManagerById.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenGettingVendorManagers.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenUpdatingVendorManager.cs, tests/Integration/Integration.Tests/VendorManagerModuleTests/WhenUpdatingVendorManagerAlreadyExists.cs
Vendor Managers & adding current Employees
=> Vendor managers

src/Service.Host/client/src/components/ChangeRequests/ChangeRequestReplace.js
=> fix display bug

src/Domain.LinnApps/Boms/BomReportsService.cs, src/Facade/Services/BomReportsFacadeService.cs, src/Facade/Services/IBomReportsFacadeService.cs, src/Service.Host/client/src/components/reports/BomCostReport.js, src/Service/Modules/BomModule.cs
no tests yet since I suspect this might not be quite what users want - just deploying as is so I can show them it for feedback
=> sort of what they want

src/Domain.LinnApps/PartSuppliers/PartSupplierService.cs, src/Domain.LinnApps/Parts/Part.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/ContextBase.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenCreatingPreferredSupplierChangeForAPartThatAlreadyHasOne.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenUpdating.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenUpdatingAndObjectFieldsNotChanged.cs, tests/Unit/Domain.LinnApps.Tests/PartTests/WhenPartHasNoStockAndCheckingShouldChangeStandardPrice.cs, tests/Unit/Domain.LinnApps.Tests/PartTests/WhenPartIsNewAndCheckingShouldChangeStandardPrice.cs
changes to part supplier service to allow changes Steph wants when
pref suppliers or price changes when there is no stock will update parts/part_history
=> ticket 20143

src/Domain.LinnApps/Parts/Part.cs, tests/Unit/Domain.LinnApps.Tests/PartSupplierServiceTests/WhenCreatingPreferredSupplierChangeForPartThatWasZeroPricedButHasStock.cs
there was a 7.7k discrepancy because we allow standards to change price to 0 and then when purchasing changed the price to something new the zero price logic kicked in for a scenario where it shouldn't have
ticket https://pchelpdesk.linn.co.uk/scp/tickets.php?id=20876#reply
=> fix ticket 20875

src/Domain.LinnApps/Reports/WhatsDueInReportService.cs
=> fix to 1 decimal place
